chore(add-files): Added README.md, LICENSE and CHANGELOG.d files
lob/litmus pull request #1
Opened 2018-07-17 17:35 UTC by shraddha1704

### What
* Added README.md, LICENSE and CHANGELOG.d files in litmus project

### Why
* Maintain good documentation and have license to make the project open source

2018-07-17 17:45 UTC, mpiercy827 reviewed
Few comments

2018-07-17 17:45 UTC, mpiercy827 commented on LICENSE
> +Copyright (c) 2018 Shraddha Sharma
Let's make this `Lob`?

2018-07-17 17:45 UTC, mpiercy827 commented on README.md
> +![Hex.pm](https://img.shields.io/hexpm/v/lazy_agent.svg)
This is the badge for `lazy_agent`, we might want to wait until we have this up on Hex before adding our badge.

2018-07-17 17:45 UTC, mpiercy827 commented on README.md
> +Data Schema validation in Elixir
how about just `Data Validation in Elixir`?

2018-07-17 17:47 UTC, mpiercy827 commented
Can you update the PR title to have an `.md` after `CHANGELOG`?

2018-07-17 17:47 UTC, shraddha1704 commented on LICENSE
> +Copyright (c) 2018 Shraddha Sharma
Sure

2018-07-17 18:03 UTC, mpiercy827 approved these changes

2018-07-18 19:02 UTC, mgartner commented on CHANGELOG.md
> +- Markdown documentation (README, LICENSE, CHANGELOG)
I think you can leave this out until you release a version. Also, I'd suggest to only include things here that are pertintent to know for users who are upgrading versions. For example, if I'm upgrade from 0.1.0 to 1.0.0, I probably don't care about whether or not the README changed, and I"m mouch more interested in how the interfaced changed and what will break.

2018-07-18 19:02 UTC, mgartner approved these changes
LGTM

2018-07-18 19:03 UTC, mgartner requested changes
Can you remove `.elixir_ls/build/test/lib/litmus/.mix/compile.lock`?

2018-07-18 20:10 UTC, mgartner approved these changes
LGTM

2018-07-18 20:14 UTC, merged